---
abstract: 'Pluggable Perl Code Metrics System'
author:
  - 'Dann <techmemo{at}gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Metrics-Lite
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  File::Basename: 0
  File::Find: 1.01
  File::Spec: 0
  Getopt::Long: 0
  IO::File: 1.14
  Module::Pluggable: 0
  PPI: 1.113
  Pod::Usage: 0
  Readonly: 1.03
  Text::ASCIITable: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
